from pathlib import Path

STARTER_AGENTS_MD = "# Project conventions\n\nAdd instructions here that both Claude Code and Codex should see.\n"
STARTER_MCP_YAML = "servers: {}\n"
STARTER_HOOKS_YAML = "hooks: {}\n"
STARTER_LOCAL_GITIGNORE = ".state/\nbackups/\n"

REPO_GITIGNORE_MARKER_START = "# --- ccx (managed) ---"
REPO_GITIGNORE_MARKER_END = "# --- end ccx ---"
REPO_GITIGNORE_BLOCK = f"""{REPO_GITIGNORE_MARKER_START}
# local ccx state (per-dev, not shared)
.ccx/.state/
.ccx/backups/

# generated by `ccx sync` — regenerated from .ccx/
/CLAUDE.md
/AGENTS.md
/.mcp.json
/.claude/
/.codex/
/.agents/
{REPO_GITIGNORE_MARKER_END}
"""


def run(scope_dir: Path, *, is_project: bool = False) -> int:
    """Create a canonical scope directory with starter files.

    When `is_project` is True, also append ccx entries to the repo root .gitignore
    (creating it if missing; idempotent via a marker block).
    """
    scope_dir.mkdir(parents=True, exist_ok=True)

    _write_if_missing(scope_dir / "AGENTS.md", STARTER_AGENTS_MD)
    _write_if_missing(scope_dir / "mcp.yaml", STARTER_MCP_YAML)
    _write_if_missing(scope_dir / "hooks.yaml", STARTER_HOOKS_YAML)
    _write_if_missing(scope_dir / ".gitignore", STARTER_LOCAL_GITIGNORE)

    for subdir in ("skills", "claude", "codex"):
        (scope_dir / subdir).mkdir(exist_ok=True)

    if is_project:
        repo_root = scope_dir.parent
        added = _ensure_repo_gitignore(repo_root / ".gitignore")
        if added:
            print(f"Added ccx block to {repo_root / '.gitignore'}")
        print(f"Initialized project scope at {scope_dir}")
    else:
        print(f"Initialized user scope at {scope_dir}")

    return 0


def _write_if_missing(path: Path, content: str) -> None:
    if not path.exists():
        path.write_text(content)


def _ensure_repo_gitignore(gitignore: Path) -> bool:
    """Append the ccx block to .gitignore if the marker isn't already present.

    Returns True if the block was added, False if it was already there.
    """
    if gitignore.exists():
        content = gitignore.read_text()
        if REPO_GITIGNORE_MARKER_START in content:
            return False
        if content and not content.endswith("\n"):
            content += "\n"
        if content and not content.endswith("\n\n"):
            content += "\n"
    else:
        content = ""

    gitignore.write_text(content + REPO_GITIGNORE_BLOCK)
    return True
